repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: file-contents-sorter
        files: .gitignore
    -   id: trailing-whitespace
-   repo:  https://github.com/jumanjihouse/pre-commit-hooks
    sha:   1.8.0
    hooks:
    -   id: shfmt
        args: ['-w', '-i', '4', '-ci']
    -   id: shellcheck
